# These are supported funding model platforms
github: madhephaestus
#github: madhephaestus 
patreon: madhephaestus
#community_bridge: BowlerStudio
issuehunt: CommonWealthRobotics/BowlerStudio
#ko-fi: bowlerstudio
liberapay: madhephaestus
#open_collective: kevin-harrington
