# These are supported funding model platforms

#github: madhephaestus 
patreon: madhephaestus
#community_bridge: BowlerStudio
issuehunt: madhephaestus
ko-fi: bowlerstudio
liberapay: madhephaestus
#open_collective: kevin-harrington
