name: "Release"
on: 
   push:
       tags:       
         - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
         submodules: recursive        
        
    - name: List directory contents
      run: pwd; ls -la      
      
    - name: start xvfb
      run:
        Xvfb :99 &

    - name: initialize the X11 DISPLAY variable
      run:
        export DISPLAY=:99

    - name: After checkout, list directory contnts
      run: pwd; ls -la        

    - name: Pull a JavaFX JDK
      run: wget http://static.azul.com/zulu/bin/zulu8.33.0.1-ca-fx-jdk8.0.192-linux_x64.tar.gz

    - name: After JDK download, list directory contnts
      run: pwd; ls -la

    - name: Set Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        jdkFile: ./zulu8.33.0.1-ca-fx-jdk8.0.192-linux_x64.tar.gz
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}   
          
    - name: Set Release Number
      run: echo $'app.name=BowlerStudio\n' > src/main/resources/com/neuronrobotics/bowlerstudio/build.properties ; echo "app.version=${{ steps.get_version.outputs.VERSION  }}" >> src/main/resources/com/neuronrobotics/bowlerstudio/build.properties 
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: "Update the Version Number on Tag"
          commit_user_name: Kevin Harrington
          commit_user_email: mad.hephaestus@gmail.com
          commit_author: Kevin Harrington <mad.hephaestus@gmail.com>  
          
    - name: Build with Gradle 
      run: ./gradlew shadowJar
      
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
            draft: false
            prerelease: false
            release_name: ${{ steps.version.outputs.version }}
            tag_name: ${{ github.ref }}
      env:
            GITHUB_TOKEN: ${{ github.token }}
            
    - name: upload BowlerStudio artifact
      uses: actions/upload-release-asset@v1
      env:
            GITHUB_TOKEN: ${{ github.token }}
      with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./build/libs/BowlerStudio.jar
            asset_name: BowlerStudio.jar
            asset_content_type: application/jar