# test
name: Test package 
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
         submodules: recursive        
        
    - name: List directory contents
      run: pwd; ls -la      
      
    - name: start xvfb
      run:
        Xvfb :0 &

    - name: initialize the X11 DISPLAY variable
      run:
        export DISPLAY=:0

    - name: After checkout, list directory contnts
      run: pwd; ls -la        

    - name: Build with Gradle 
      run: bash makeJar.sh
